### PR TITLE
Ops 9006 gha tests

### PR DESCRIPTION
**Pull request by lazysoundsystem**
Refs: OPS-9006

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
Note: As with https://github.com/UN-OCHA/cerf8/pull/1120 - code coverage isn't working here - it's commented out for the moment as I hope to be able to fix it later.

**Comment by cafuego** [comment]
As long as there is a ticket to remind us to fix it, sure :-)

**Comment by lazysoundsystem** [comment]
Here we go: https://humanitarian.atlassian.net/browse/OPS-9384

**Review by cafuego — APPROVED** [review]
👍 boop!

**Pull request merged**
